workflows:
  android_apk:
    name: Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Post-clone setup (generate android, minSdk 24, Jitsi repo, permissions)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "== Post-clone =="
          flutter --version

          # 1) Create platform folders if missing
          if [ ! -f "android/settings.gradle" ]; then
            echo "Generating Flutter platform scaffolds..."
            flutter create .
          fi

          # 2) Ensure minSdkVersion 24 for Jitsi
          APP_GRADLE="android/app/build.gradle"
          if grep -q "minSdkVersion" "$APP_GRADLE"; then
            tmpfile="$(mktemp)"
            sed 's/minSdkVersion[[:space:]]\+[0-9a-zA-Z_.-]\+/minSdkVersion 24/g' "$APP_GRADLE" > "$tmpfile"
            mv "$tmpfile" "$APP_GRADLE"
          else
            awk '/defaultConfig[[:space:]]*\{/{print;print "        minSdkVersion 24";next}1' "$APP_GRADLE" > "$APP_GRADLE.tmp" && mv "$APP_GRADLE.tmp" "$APP_GRADLE"
          fi

          # 3) Add Internet/Camera/Mic permissions if missing
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
            awk '{
              if ($0 ~ /<application/) {
                print "    <uses-permission android:name=\"android.permission.INTERNET\"/>";
                print "    <uses-permission android:name=\"android.permission.CAMERA\"/>";
                print "    <uses-permission android:name=\"android.permission.RECORD_AUDIO\"/>";
              }
              print $0
            }' "$MANIFEST" > "$MANIFEST.tmp" && mv "$MANIFEST.tmp" "$MANIFEST"
          fi

          # 4) Inject Jitsi Maven repo if missing
          SETTINGS="android/settings.gradle"
          JITSI='maven { url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" }'
          if ! grep -q 'jitsi-maven-repository' "$SETTINGS"; then
            awk -v J="$JITSI" '
              /pluginManagement[[:space:]]*\{/ {pm=1}
              /dependencyResolutionManagement[[:space:]]*\{/ {drm=1}
              {
                print
                if (pm && /repositories[[:space:]]*\{/ ) { print "        " J }
                if (drm && /repositories[[:space:]]*\{/ ) { print "        " J }
              }
            ' "$SETTINGS" > "$SETTINGS.tmp" && mv "$SETTINGS.tmp" "$SETTINGS"
          fi

          echo "== Post-clone complete =="
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
