name: meditour_app_menu_mvp
description: "Menu UI MVP: auth+OTP+locale, chatbot (TTS), Jitsi consult, quotation, doctors, compliance."
publish_to: "none"
version: 0.2.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  flutter_tts: ^4.0.2
  jitsi_meet_flutter_sdk: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/knowledge/turkey_medical_tourism.json
