import 'package:flutter/material.dart';import '../../services/mock_api.dart';
class QuotationPage extends StatefulWidget{const QuotationPage({super.key});@override State<QuotationPage> createState()=>_S();}
class _S extends State<QuotationPage>{final _pre=TextEditingController(),_notes=TextEditingController();String _type='Dental',_city='Istanbul';bool _visa=false,_transport=false,_hotel=false,_loading=false;
 @override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('Quotation Request')),drawer:Drawer(child:ListView(children:[const DrawerHeader(child:Text('MediTour')),ListTile(leading:const Icon(Icons.home),title:const Text('Home'),onTap:()=>Navigator.pushReplacementNamed(c,'/home'))])),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
  DropdownButtonFormField(value:_type,decoration:const InputDecoration(labelText:'Treatment type'),items:const['Dental','Hair','Cosmetic','Orthopedic'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>_type=v??'Dental')),const SizedBox(height:12),
  DropdownButtonFormField(value:_city,decoration:const InputDecoration(labelText:'Preferred city'),items:const['Istanbul','Ankara','Antalya'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>_city=v??'Istanbul')),const SizedBox(height:12),
  const Text('Options'),CheckboxListTile(value:_visa,onChanged:(v)=>setState(()=>_visa=v??false),title:const Text('Visa invitation letter')),CheckboxListTile(value:_transport,onChanged:(v)=>setState(()=>_transport=v??false),title:const Text('Transportation')),CheckboxListTile(value:_hotel,onChanged:(v)=>setState(()=>_hotel=v??false),title:const Text('Hotel booking')),
  const SizedBox(height:12),TextField(controller:_pre,decoration:const InputDecoration(labelText:'Any medical preconditions'),maxLines:2),const SizedBox(height:12),TextField(controller:_notes,decoration:const InputDecoration(labelText:'Notes'),maxLines:3),const SizedBox(height:16),
  SizedBox(width:double.infinity,child: FilledButton(onPressed:_loading?null:() async{setState(()=>_loading=True)}, child:Text(_loading?'...':'Send request'))),
 ])));}
}
